### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by hankecnc** [shooter64738/Talos-CNC#9]
Hello, I am a diy cnc enthusiast from China, my job is a CNC mechanic, I have been looking for a low cost embedded cnc controller to replace mach3 or linuxcnc, I have tried grbl and stm32f446 versions of grblhal, grblhal is good, he has gap compensation, but he doesn't support radius compensation, it's really bad,

**Comment by hankecnc** [comment]
The ideal CNC system in my mind should be a model like grbl, where G code interpretation and motion control run in a powerful 32-bit microcontroller, and the host computer only handles user input

**Comment by hankecnc** [comment]
I'm not a software engineer, so I don't know the software code very well, but I can help this project to promote, that is, to make the circuit board for this project for sale, I learned to draw circuit boards in my spare time, and made esp32 grbl circuit boards Low price, it's not bad at the moment, but I'm not satisfied, I know very well that esp32 grbl is only suitable for small and cheap cnc, writing machine, laser, he is not very professional, there is no radius compensation

**Comment by hankecnc** [comment]
Seems to be dead

**Comment by shooter64738** [comment]
It's most definitely not dead. I work on it by myself as time allows and don't check in as frequently as I did.

But it's still going....

**Comment by shooter64738** [comment]
The process of this control is based on the GE Fanuc control.
Gcode is sent to the controller and converted to machine motion per line. But no motion executes until cycle start is selected. This allows the control to error check, and generate any compensation motions needed for tool offsets or crc. Any conflicting tool paths are found.

The host PC need not be attached, except to monitor what the control is doing. Gcode could be loaded from an SD card if needed, or via network connection.

The motion is processed on a dual core stm32 processor.

**Comment by hankecnc** [comment]
I want to communicate with you, I don't know your purpose of making Talos-CNC, my idea is to make a cheap and professional CNC system that can replace mach3 and linuxcnc, mach3 and linuxcnc are complicated and old , and grbl does not support radius compensation, it is not professional, if Talos-CNC is easy to use, it can go to closed source charging mode, I have not tested it yet, I will not even compile it, I am familiar with grbl now

**Comment by hankecnc** [comment]
My ideal CNC system, the host computer is responsible for displaying data information, processing user input, sending G code to Talos-CNC for execution, using arm linux+qt to make the host computer is a good choice, its cost is very low, in our This can buy very cheap Allwinner chips, and a new very cheap SSD202, dual-core A7, only 38 RMB
![aa](https://user-images.githubusercontent.com/69781416/159193734-c6bd3d05-ab95-4992-82b7-5b060e3e27a3.png)

**Comment by hankecnc** [comment]
I found a way to compile on this page https://github.com/shooter64738/Talos-CNC/issues/1, I will try it first

**Comment by shooter64738** [comment]
The purpose of talos is to create a professional grade cnc control with functions and features found in professional controls.

There are/were many ports of grbl to other hardware devices. However it is still the same system running on a faster/different processor. Something such as cutter radius compensation cannot happen on a control that does not look at least 1 line ahead. Since grbl is drop feed from a host it cannot perform crc. There are some things it does well. I'm bot knocking the firmware, it just has limits.

Talos works similar too the Fanuc control. The parameters and settings are based on the Fanuc control types. 

I've spent almost 10 years on this firmware now. Many refactors, rewrites, updates, hardware changes, etc. But it's only been me working on it at this point, so I work on it when I can.

**Comment by hankecnc** [comment]
Well, it's a little bit hard for me to compile it, just compiled Talos_HMI successfully, downloaded Microchip Studio and compiled it with an error, I'm not familiar with him, but none of this matters, now I need to test it,

What should I use to test it? I can buy mega2560 and sam3x8e in the market, I also have stm32f446, do you know if the f4 in your project can run on the f446? Or is your f4 a specific model? I can Buy it and draw a PCB to make a minimal test board, STMH745 I won't consider him, it's too unpopular and expensive
![Screenshot_20220321_111221](https://user-images.githubusercontent.com/69781416/159201409-3d531743-df6a-4788-8471-cda65d5728b3.jpg)
![Screenshot_20220321_111612](https://user-images.githubusercontent.com/69781416/159201410-bff18546-936e-4c8e-9996-2a27d1fd59ed.jpg)

**Comment by hankecnc** [comment]
stm32H750或者H743也可以考虑,

**Comment by hankecnc** [comment]
stm32H750 or H743 can also be considered,

**Comment by hankecnc** [comment]
In addition, is the five-axis rtcp easy to implement? There are many diy enthusiasts in China looking for a five-axis rtcp controller. If it can be realized, its price can be very high, and I can help you sell it in China

**Comment by shooter64738** [comment]
This project outgrew the arudino mega several year ago. 

The STM32F4 chip series is the low end of the chips that can run this firmware, and that port isnt totaly done yet. I built this to run on an STM32H7 chip as the dual cores provide faster processing and pulse outputs. The boards are ready made and available on ebay. There is a major chip shortage right now and the prices are higher than they were, but still affordable.

This is similar to the board I use for development:
[https://www.ebay.com/itm/383879695232](ebay stm32 board)

The HMI runs on any windows pc, but was designed to run on a thumb pc with a minimum 7" touch screen. The control can also be configured on any standard pc and teh settings downloaded to the control.

I wouldnt say the project is ready for building a board at this time. There are still things I need to work out in the firmware to get it to behave in certain modes. I also need to finish the turning, pick-n-place,, and plasma modifications.

I appreciate your enthusiasm, and if you want to get started with it, I'll help you as much as I can. Debugging is something I haven't had much chance to do lately, and it does need to be in use to work out different kinks in it.

**Comment by hankecnc** [comment]
> This project outgrew the arudino mega several year ago.
> 
> The STM32F4 chip series is the low end of the chips that can run this firmware, and that port isnt totaly done yet. I built this to run on an STM32H7 chip as the dual cores provide faster processing and pulse outputs. The boards are ready made and available on ebay. There is a major chip shortage right now and the prices are higher than they were, but still affordable.
> 
> This is similar to the board I use for development: [ebay stm32 board](https://www.ebay.com/itm/383879695232)
> 
> The HMI runs on any windows pc, but was designed to run on a thumb pc with a minimum 7" touch screen. The control can also be configured on any standard pc and teh settings downloaded to the control.
> 
> I wouldnt say the project is ready for building a board at this time. There are still things I need to work out in the firmware to get it to behave in certain modes. I also need to finish the turning, pick-n-place,, and plasma modifications.
> 
> I appreciate your enthusiasm, and if you want to get started with it, I'll help you as much as I can. Debugging is something I haven't had much chance to do lately, and it does need to be in use to work out different kinks in it.

Since the beginning of the epidemic, the price of low-end products such as STM32F103C8T6 has increased several times, but the price of the H7 series has not increased, but I don't know if it was recently or when, the chips of the H7 system also began to skyrocket.

**Comment by hankecnc** [comment]
> This project outgrew the arudino mega several year ago.
> 
> The STM32F4 chip series is the low end of the chips that can run this firmware, and that port isnt totaly done yet. I built this to run on an STM32H7 chip as the dual cores provide faster processing and pulse outputs. The boards are ready made and available on ebay. There is a major chip shortage right now and the prices are higher than they were, but still affordable.
> 
> This is similar to the board I use for development: [ebay stm32 board](https://www.ebay.com/itm/383879695232)
> 
> The HMI runs on any windows pc, but was designed to run on a thumb pc with a minimum 7" touch screen. The control can also be configured on any standard pc and teh settings downloaded to the control.
> 
> I wouldnt say the project is ready for building a board at this time. There are still things I need to work out in the firmware to get it to behave in certain modes. I also need to finish the turning, pick-n-place,, and plasma modifications.
> 
> I appreciate your enthusiasm, and if you want to get started with it, I'll help you as much as I can. Debugging is something I haven't had much chance to do lately, and it does need to be in use to work out different kinks in it.

Do you mean dual core CPU, one for computing and the other for pulsing? If your project is good enough, expensive H7 is acceptable too

**Comment by shooter64738** [comment]
The M7 core is used to parse gcode, convert parameters to true values, load/store tool offsets, calculate cutter comp, convert gcode to binary line data, store/load line data. The M4 core does nothing until a motion is needed. M7 loads line data and sends to the M4 core which generates step information.

The process used to be accomplished with a pair of independent processors, but this simplified it some. I need to be able to generate pulses very fast (1mhz is the minimum target) in order to have high speed and high precision. Most stepper drivers cannot handle 1mhz pulse rates, but several servo systems can. It can always be slowed down, but I needed the high max rate.

**Comment by hankecnc** [comment]
> The M7 core is used to parse gcode, convert parameters to true values, load/store tool offsets, calculate cutter comp, convert gcode to binary line data, store/load line data. The M4 core does nothing until a motion is needed. M7 loads line data and sends to the M4 core which generates step information.
> 
> The process used to be accomplished with a pair of independent processors, but this simplified it some. I need to be able to generate pulses very fast (1mhz is the minimum target) in order to have high speed and high precision. Most stepper drivers cannot handle 1mhz pulse rates, but several servo systems can. It can always be slowed down, but I needed the high max rate.



> The M7 core is used to parse gcode, convert parameters to true values, load/store tool offsets, calculate cutter comp, convert gcode to binary line data, store/load line data. The M4 core does nothing until a motion is needed. M7 loads line data and sends to the M4 core which generates step information.
> 
> The process used to be accomplished with a pair of independent processors, but this simplified it some. I need to be able to generate pulses very fast (1mhz is the minimum target) in order to have high speed and high precision. Most stepper drivers cannot handle 1mhz pulse rates, but several servo systems can. It can always be slowed down, but I needed the high max rate.

**Comment by hankecnc** [comment]
?Why didn't you reply to me?

**Comment by shooter64738** [comment]
You can. Test with it. There's still portions of it I need to work on.

I work a regular job, and I sleep at night. I respond when I can, same as I work on the firmware when I can.

**Comment by hankecnc** [comment]
ok, ok, I thought you gave up on this project yourself, please contact me when you have time, a little busy recently,
